import time
from queue import Queue as ThreadQueue
from typing import Optional, Dict, Any, Generic, TypeVar
from pydantic import BaseModel, Field

T = TypeVar("T")


try:
    from crewai.flow.flow import Flow, start, listen
except ImportError:
    class Flow(Generic[T]):  # type: ignore
        def __init__(self, **kwargs):
            if not hasattr(self, "state") or self.state is None:
                self.state = FlowState()

        def kickoff(self):
            if hasattr(self, "execute_input_step"):
                self.execute_input_step()
            if hasattr(self, "execute_db_step"):
                self.execute_db_step()
            if hasattr(self, "execute_analytics_step"):
                self.execute_analytics_step()
            if hasattr(self, "execute_output_step"):
                self.execute_output_step()

    def start():
        def decorator(fn):
            return fn
        return decorator

    def listen(other_fn):
        def decorator(fn):
            return fn
        return decorator

from app.mother.state import WorkflowState
from app.agents.registry import AgentRegistry
from app.mother.task_manager import TaskManager
from app.contracts import OrchestrationEvent


class FlowState(BaseModel):
    workflow: Optional[WorkflowState] = None
    step_results: Dict[str, Any] = Field(default_factory=dict)


class AgentCampusFlow(Flow[FlowState]):
    """Internal CrewAI Flow executing the exact DynamicPlan generated by MotherAgent."""

    def __init__(
        self,
        workflow: WorkflowState,
        registry: Optional[AgentRegistry] = None,
        event_queue: Optional[ThreadQueue] = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.state.workflow = workflow
        self.registry = registry or AgentRegistry()
        self.task_manager = TaskManager()
        self.event_queue = event_queue  # Optional: for incremental SSE streaming

    def _emit(self, event: OrchestrationEvent) -> None:
        """Push an event to the streaming queue if one is attached."""
        if self.event_queue is not None:
            self.event_queue.put(event)

    @start()
    def execute_input_step(self):
        wf = self.state.workflow
        if not wf or not wf.plan:
            return
        if not any(s.agent == "input" for s in wf.plan.steps):
            return

        self._emit(OrchestrationEvent(
            type="AGENT_STARTED",
            task_id=wf.workflow_id,
            timestamp=time.time(),
            agent_id="input",
            message="Input Agent: parsing natural language query...",
        ))

        task = self.task_manager.create_task(
            agent="input",
            objective="Understand user query",
            input_data={"user_query": wf.user_query, "mode": wf.mode, "confirmed": wf.confirmed},
            expected_output="Structured query intent",
        )
        agent = self.registry.get("input")
        result = agent.execute(task)

        if result.status == "completed":
            self.task_manager.update_task_status(task, "completed")
            wf.task_history.append(task)
            self.state.step_results["input"] = result.result
            wf.results["input"] = result.result
            self._emit(OrchestrationEvent(
                type="AGENT_COMPLETED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="input",
                message="Input Agent: query intent extracted",
            ))
        else:
            self.task_manager.update_task_status(task, "failed")
            wf.task_history.append(task)
            self._emit(OrchestrationEvent(
                type="AGENT_FAILED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="input",
                message="Input Agent failed",
            ))

    @listen(execute_input_step)
    def execute_db_step(self):
        wf = self.state.workflow
        if not wf or not wf.plan:
            return
        if not any(s.agent == "db" for s in wf.plan.steps):
            return

        self._emit(OrchestrationEvent(
            type="AGENT_STARTED",
            task_id=wf.workflow_id,
            timestamp=time.time(),
            agent_id="db",
            message="DB Agent: querying campus database...",
        ))

        task = self.task_manager.create_task(
            agent="db",
            objective="Execute SQL query on campus database",
            input_data={"user_query": wf.user_query, "mode": wf.mode, "confirmed": wf.confirmed, **self.state.step_results},
            expected_output="Database records",
        )

        agent = self.registry.get("db")
        result = agent.execute(task)

        if result.status == "completed":
            self.task_manager.update_task_status(task, "completed")
            wf.task_history.append(task)
            self.state.step_results["db"] = result.result
            wf.results["db"] = result.result
            self._emit(OrchestrationEvent(
                type="AGENT_COMPLETED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="db",
                message=f"DB Agent: retrieved {result.result.get('count', 0)} records",
            ))
        else:
            self.task_manager.update_task_status(task, "failed")
            wf.task_history.append(task)
            self._emit(OrchestrationEvent(
                type="AGENT_FAILED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="db",
                message="DB Agent failed",
            ))

    @listen(execute_db_step)
    def execute_analytics_step(self):
        wf = self.state.workflow
        if not wf or not wf.plan:
            return
        # Strictly check MotherAgent's plan — never independently add analytics
        if not any(s.agent == "analytics" for s in wf.plan.steps):
            return
        if self.state.step_results.get("db", {}).get("requires_confirmation"):
            return

        self._emit(OrchestrationEvent(
            type="AGENT_STARTED",
            task_id=wf.workflow_id,
            timestamp=time.time(),
            agent_id="analytics",
            message="Analytics Agent: computing statistical metrics...",
        ))

        task = self.task_manager.create_task(
            agent="analytics",
            objective="Compute statistical metrics",
            input_data={"user_query": wf.user_query, "mode": wf.mode, "confirmed": wf.confirmed, **self.state.step_results},
            expected_output="Analytics metrics",
        )
        agent = self.registry.get("analytics")
        result = agent.execute(task)

        if result.status == "completed":
            self.task_manager.update_task_status(task, "completed")
            wf.task_history.append(task)
            self.state.step_results["analytics"] = result.result
            wf.results["analytics"] = result.result
            self._emit(OrchestrationEvent(
                type="AGENT_COMPLETED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="analytics",
                message="Analytics Agent: metrics computed",
            ))
        else:
            self.task_manager.update_task_status(task, "failed")
            wf.task_history.append(task)
            self._emit(OrchestrationEvent(
                type="AGENT_FAILED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="analytics",
                message="Analytics Agent failed",
            ))

    @listen(execute_analytics_step)
    def execute_output_step(self):
        wf = self.state.workflow
        if not wf or not wf.plan:
            return
        if self.state.step_results.get("db", {}).get("requires_confirmation"):
            return
        if not any(s.agent == "output" for s in wf.plan.steps):
            return

        self._emit(OrchestrationEvent(
            type="AGENT_STARTED",
            task_id=wf.workflow_id,
            timestamp=time.time(),
            agent_id="output",
            message="Output Agent: formatting response payload...",
        ))

        task = self.task_manager.create_task(
            agent="output",
            objective="Format summary table and response payload",
            input_data={"user_query": wf.user_query, "mode": wf.mode, "confirmed": wf.confirmed, **self.state.step_results},
            expected_output="Formatted response payload",
        )

        agent = self.registry.get("output")
        result = agent.execute(task)

        if result.status == "completed":
            self.task_manager.update_task_status(task, "completed")
            wf.task_history.append(task)
            self.state.step_results["output"] = result.result
            wf.results["output"] = result.result
            self._emit(OrchestrationEvent(
                type="AGENT_COMPLETED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="output",
                message="Output Agent: response formatted",
            ))
        else:
            self.task_manager.update_task_status(task, "failed")
            wf.task_history.append(task)
            self._emit(OrchestrationEvent(
                type="AGENT_FAILED",
                task_id=wf.workflow_id,
                timestamp=time.time(),
                agent_id="output",
                message="Output Agent failed",
            ))
